version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: storygame-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - storygame_net

  backend:
    image: sulitha/storygame-backend:latest
    container_name: storygame-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URI=mongodb://mongo:27017/storygame
    depends_on:
      - mongo
    networks:
      - storygame_net

  frontend:
    image: sulitha/storygame-frontend:latest
    container_name: storygame-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - storygame_net

volumes:
  mongo_data:

networks:
  storygame_net:
    driver: bridge
